### PR TITLE
Fix disconnect account behavior

### LINKED ISSUE #19: [GitHub Add-on] Disconnect flow doesn't work
The Disconnect account flow doesn't work in the GitHub add-on if you don't sign in with another GitHub account.

Repro:

1) Install the add-on and sign in with a GitHub account.
2) Go to the Settings screen and click "DISCONNECT ACCOUNT".
3) When prompted to sign in with another GitHub account, close the add-on.
4) Open add-on again on another email.

Expected:

The GitHub account is disconnected and you'll be prompted to log in again.

Actual:

The GitHub account isn't disconnected.

### PR DESCRIPTION
**Pull request by sqrrrl**
Update disconnect account to properly invalidate token (previously just deleted it from internal storage,) disable back button in card stack. Fixes #19, #28

### CODE REVIEW

File: github/src/ActionHandlers.js [hunk 1]
```diff
@@ -69,14 +69,25 @@ var ActionHandlers = {
         .build();
   },
 
+
```
Comment (asrivas) [inline github/src/ActionHandlers.js]: nit
